# Site settings
title: Yasir Lateef
description: Software Engineer
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://yasirlateef.github.io" # the base hostname & protocol for your site e.g.

# User settings
username: Yasir Lateef
user_description: I'm a nomad Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in <strong>React Native</strong>, working for Dapper Apps, a Perth-based startup, trying to create the domain-perfect mobile applications. I'm one of the three guys behind all the JS related stuff.
user_title: Software Engineer
email: yasirlateef112@gmail.com
facebook_username: ysrltf1
instagram_username: yasrlatf
twitter_username: yasrlatf
github_username:  yasirlateef
linkedin_username: yasirlateef
# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
